name: Webhook Notify
on:
  release:
      types: [published]
      jobs:
        webhook:
            runs-on: ubuntu-latest
                steps:
                      - run: curl -X POST "${{ secrets.Release_Notification }}" -H "Content-Type: application/json" -d '{"content":"Filelo ${{ github.event.release.tag_name }} released!"}'
